#!/usr/bin/env python3
"""Box plots of core firing-rate/selectivity metrics split by incoming weight cohorts.

Extended Data companion to Figure 5 (which uses outgoing cohorts).
Cohort node sets are generated by:
  analysis_shared/create_highlow_incoming_weight_nodesets.py
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

import matplotlib.colors as mcolors
import matplotlib.pyplot as plt
import h5py
import numpy as np
import pandas as pd
import seaborn as sns

# =============================================================================
# Plot settings
# =============================================================================
FIGSIZE_SINGLE = (5, 4)
FIGSIZE_COMBINED = (6, 4)
FR_YMAX = 40

SINGLE_XLABEL_FS = 18
SINGLE_YLABEL_FS = 18

COMBINED_YLABEL_FS = 18
COMBINED_XTICK_FS = 18
COMBINED_XTICK_PAD = 0

CELLTYPE_FIRST_TICK_FS = 17
CELLTYPE_FIRST_GROUP_LABEL_FS = 18
CELLTYPE_FIRST_GROUP_LABEL_Y = -0.20

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent.parent
OUTPUT_DIR = PROJECT_ROOT / "figures" / "paper" / "extended_data" / "incoming_cohorts"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

FEATURES_PATH = (
    PROJECT_ROOT / "cell_categorization" / "core_nll_0_neuron_features.parquet"
)
NETWORKS: List[Tuple[str, str, str]] = [
    ("bio_trained", "Bio-trained", "OSI_DSI_DF_bio_trained.csv"),
    ("plain", "Plain", "OSI_DSI_DF_plain.csv"),
]
CORE_RADIUS = 200.0

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from network_utils import load_nodes

CELL_CLASSES: Dict[str, Dict[str, Iterable[str]]] = {
    "Exc": {
        "files": {
            "high": "high_incoming_exc_core_nodes.json",
            "low": "low_incoming_exc_core_nodes.json",
        },
        "matches": ("Exc", "IT", "ET", "NP"),
    },
    "PV": {
        "files": {
            "high": "pv_high_incoming_core_nodes.json",
            "low": "pv_low_incoming_core_nodes.json",
        },
        "matches": ("PV", "Pvalb"),
    },
    "SST": {
        "files": {
            "high": "sst_high_incoming_core_nodes.json",
            "low": "sst_low_incoming_core_nodes.json",
        },
        "matches": ("SST", "Sst"),
    },
    "VIP": {
        "files": {
            "high": "vip_high_incoming_core_nodes.json",
            "low": "vip_low_incoming_core_nodes.json",
        },
        "matches": ("VIP", "Vip"),
    },
}

METRICS = [
    ("rate", "Average firing rate (Hz)", "incoming_rate_by_cohort"),
    ("OSI", "OSI", "incoming_osi_by_cohort"),
    ("DSI", "DSI", "incoming_dsi_by_cohort"),
    ("dg_sparsity", "DG trial-averaged sparsity", "incoming_dg_sparsity_by_cohort"),
    ("image_selectivity", "Image selectivity", "incoming_image_selectivity_by_cohort"),
]

TRAINING_LABELS = {
    "bio_trained": "trained",
    "plain": "untrained",
}

COHORT_COLORS = {
    "low": "#2b7bba",
    "mid": "#888888",
    "high": "#c73635",
}


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(
        description="Extended Data boxplots for rates/selectivity split by incoming weight cohorts."
    )
    ap.add_argument(
        "--base-dir",
        type=Path,
        default=None,
        help=(
            "If provided, generate plots for a single network directory (e.g. core_nll_0). "
            "If omitted, aggregate across core_nll_0..9 (default behavior)."
        ),
    )
    ap.add_argument(
        "--output-dir",
        type=Path,
        default=OUTPUT_DIR,
        help="Directory to store the generated figures.",
    )
    ap.add_argument(
        "--combined-only",
        action="store_true",
        help="Only generate the combined bio-vs-plain panels (skip per-network panels).",
    )
    ap.add_argument(
        "--group-order",
        choices=["training_first", "celltype_first"],
        default="celltype_first",
        help="Combined-panel x-axis hierarchy.",
    )
    ap.add_argument(
        "--hide-outliers",
        action="store_true",
        help="Hide outliers (fliers) on boxplots.",
    )
    return ap.parse_args()


def _discover_base_dirs() -> List[Path]:
    base_dirs: List[Path] = []
    for i in range(10):
        d = PROJECT_ROOT / f"core_nll_{i}"
        if d.exists():
            base_dirs.append(d)
    return base_dirs


def _load_node_ids(base_dir: Path) -> np.ndarray:
    node_file = base_dir / "network" / "v1_nodes.h5"
    with h5py.File(node_file, "r") as f:
        return f["nodes"]["v1"]["node_id"][:].astype(np.int64)


def load_features(base_dir: Path) -> pd.DataFrame:
    nodes_df = load_nodes(str(base_dir), loc="v1", expand=True)
    nodes_df = nodes_df.copy()
    center_x = float(np.median(nodes_df["x"]))
    center_z = float(np.median(nodes_df["z"]))
    nodes_df["radius"] = np.sqrt(
        (nodes_df["x"] - center_x) ** 2 + (nodes_df["z"] - center_z) ** 2
    )
    features = nodes_df[["cell_type", "radius"]].copy()

    if FEATURES_PATH.exists():
        try:
            extra = pd.read_parquet(FEATURES_PATH).set_index("node_id")
            if "image_selectivity" in extra.columns:
                features = features.join(extra[["image_selectivity"]], how="left")
        except Exception:
            pass

    if "image_selectivity" not in features.columns:
        features["image_selectivity"] = np.nan

    return features


def load_sparsity(base_dir: Path, node_ids: np.ndarray, network: str) -> pd.Series:
    metrics_dir = base_dir / "metrics"
    cache = metrics_dir / f"dg_trial_averaged_sparsity_{network}.npy"
    if not cache.exists() and network == "bio_trained":
        cache = metrics_dir / "dg_trial_averaged_sparsity.npy"

    if cache.exists():
        sparsity = np.load(cache)
        if len(sparsity) == len(node_ids):
            series = pd.Series(sparsity, index=node_ids, name="dg_sparsity")
            series.index.name = "node_id"
            return series

    print(f"Warning: DG sparsity cache not found for {network} in {base_dir} or length mismatch.")
    series = pd.Series(np.nan, index=node_ids, name="dg_sparsity")
    series.index.name = "node_id"
    return series


def load_node_ids_from_file(base_dir: Path, filename: str) -> set[int]:
    path = base_dir / "node_sets" / filename
    if not path.exists():
        return set()
    df = pd.read_json(path)
    return set(map(int, df["node_id"]))


def matches_any(text: str, tokens: Iterable[str]) -> bool:
    return any(token in text for token in tokens)


def build_cohort_table(base_dir: Path, features: pd.DataFrame) -> pd.DataFrame:
    core_ids = set(features.index[features["radius"] <= CORE_RADIUS])
    rows: List[Tuple[int, str, str]] = []

    for label, info in CELL_CLASSES.items():
        tokens = info["matches"]
        mask = (
            features["cell_type"].fillna("").apply(lambda txt: matches_any(txt, tokens))
        )
        ids = set(map(int, features.index[mask])) & core_ids
        if not ids:
            continue

        high_ids = load_node_ids_from_file(base_dir, info["files"]["high"])
        low_ids = load_node_ids_from_file(base_dir, info["files"]["low"])

        for node_id in ids:
            if node_id in high_ids:
                cohort = "high"
            elif node_id in low_ids:
                cohort = "low"
            else:
                cohort = "mid"
            rows.append((node_id, label, cohort))

    cohort_df = pd.DataFrame(rows, columns=["node_id", "cell_class", "cohort"])

    inh_rows = cohort_df[cohort_df["cell_class"].isin(["PV", "SST", "VIP"])]
    if not inh_rows.empty:
        inh_added = inh_rows.copy()
        inh_added["cell_class"] = "Inh"
        cohort_df = pd.concat([cohort_df, inh_added], ignore_index=True)

    cohort_df = cohort_df[cohort_df["cell_class"].isin(["Exc", "Inh"])]

    return cohort_df


def load_metrics_table(metrics_file: Path) -> pd.DataFrame:
    df = pd.read_csv(metrics_file, sep=" ")
    df = df.rename(
        columns={
            "Ave_Rate(Hz)": "rate",
            "max_mean_rate(Hz)": "max_rate",
        }
    )
    return df


def make_boxplot(
    df: pd.DataFrame, title: str, metric_col: str, metric_label: str, tag: str,
    out_dir: Path,
) -> None:
    sns.set(style="whitegrid", context="talk")
    order = [c for c in ["Exc", "Inh"] if c in df["cell_class"].unique()]
    if not order:
        print(f"No data for {title}; skipping plot")
        return

    fig, ax = plt.subplots(figsize=FIGSIZE_SINGLE)
    sns.boxplot(
        data=df,
        x="cell_class",
        y=metric_col,
        hue="cohort",
        order=order,
        hue_order=["low", "mid", "high"],
        palette=COHORT_COLORS,
        showfliers=True,
        ax=ax,
    )
    ax.set_xlabel("Cell class", fontsize=SINGLE_XLABEL_FS)
    ax.set_ylabel(metric_label, fontsize=SINGLE_YLABEL_FS)
    if metric_col == "rate":
        ax.set_ylim(0, FR_YMAX)
    if ax.get_legend() is not None:
        ax.get_legend().remove()
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    plt.tight_layout()
    out_png = out_dir / f"{tag}.png"
    out_pdf = out_dir / f"{tag}.pdf"
    fig.savefig(out_png, dpi=300)
    fig.savefig(out_pdf)
    plt.close(fig)
    print(f"Saved {title} to {out_png}")


def _lighten_color(color, amount: float = 0.35):
    r, g, b, *rest = mcolors.to_rgba(color)
    r = 1 - amount * (1 - r)
    g = 1 - amount * (1 - g)
    b = 1 - amount * (1 - b)
    if rest:
        return (r, g, b, rest[0])
    return (r, g, b)


def make_combined_boxplot(
    df: pd.DataFrame,
    metric_col: str,
    metric_label: str,
    filename_prefix: str,
    *,
    out_dir: Path,
    out_suffix: str = "",
    showfliers: bool = True,
    group_order: str = "training_first",
    ylim: Tuple[float, float] | None = None,
) -> None:
    sns.set(style="whitegrid", context="talk")
    if group_order == "celltype_first":
        order_all = [
            "Exc (untrained)",
            "Exc (trained)",
            "Inh (untrained)",
            "Inh (trained)",
        ]
    else:
        order_all = [
            "Exc (untrained)",
            "Inh (untrained)",
            "Exc (trained)",
            "Inh (trained)",
        ]
    present_order = [c for c in order_all if c in df["cell_class_training"].unique()]
    if not present_order:
        print(f"No data for combined {metric_col}; skipping plot")
        return

    hue_order = ["low", "mid", "high"]
    palette = {k: COHORT_COLORS[k] for k in hue_order}

    fig, ax = plt.subplots(figsize=FIGSIZE_COMBINED)
    sns.boxplot(
        data=df,
        x="cell_class_training",
        y=metric_col,
        hue="cohort",
        order=present_order,
        hue_order=hue_order,
        palette=palette,
        showfliers=showfliers,
        ax=ax,
    )

    boxes_per_group = len(hue_order)
    for idx, artist in enumerate(ax.artists):
        group_idx = idx // boxes_per_group
        if group_idx < len(present_order) and "untrained" in present_order[group_idx]:
            artist.set_facecolor(_lighten_color(artist.get_facecolor(), amount=0.45))
            artist.set_alpha(0.8)

    ax.set_xlabel("")
    ax.set_ylabel(metric_label, fontsize=COMBINED_YLABEL_FS)
    if ylim:
        ax.set_ylim(ylim)

    ticks = list(range(len(present_order)))
    ax.set_xticks(ticks)
    if group_order == "celltype_first":
        ax.set_xticklabels(
            ["Untrained", "Trained", "Untrained", "Trained"][: len(ticks)],
            fontsize=CELLTYPE_FIRST_TICK_FS,
        )
        if len(ticks) >= 4:
            y_ct = CELLTYPE_FIRST_GROUP_LABEL_Y
            ct_fs = CELLTYPE_FIRST_GROUP_LABEL_FS
            exc_center = (ticks[0] + ticks[1]) / 2
            inh_center = (ticks[2] + ticks[3]) / 2
            ax.text(
                exc_center, y_ct, "Exc",
                ha="center", va="center",
                transform=ax.get_xaxis_transform(), fontsize=ct_fs,
            )
            ax.text(
                inh_center, y_ct, "Inh",
                ha="center", va="center",
                transform=ax.get_xaxis_transform(), fontsize=ct_fs,
            )
            ax.tick_params(axis="x", pad=COMBINED_XTICK_PAD)
    else:
        ax.set_xticklabels(
            [lbl.split(" ")[0] for lbl in present_order], fontsize=COMBINED_XTICK_FS
        )
        if len(ticks) >= 4:
            untrained_center = (ticks[0] + ticks[1]) / 2
            trained_center = (ticks[-2] + ticks[-1]) / 2
            y_text = -0.08
            ax.text(
                untrained_center, y_text, "Untrained",
                ha="center", va="center",
                transform=ax.get_xaxis_transform(), fontsize=16,
            )
            ax.text(
                trained_center, y_text, "Trained",
                ha="center", va="center",
                transform=ax.get_xaxis_transform(), fontsize=16,
            )
            ax.tick_params(axis="x", pad=18)
    if ax.get_legend() is not None:
        ax.get_legend().remove()
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    plt.tight_layout()
    out_png = out_dir / f"{filename_prefix}_bio_vs_plain{out_suffix}.png"
    out_pdf = out_dir / f"{filename_prefix}_bio_vs_plain{out_suffix}.pdf"
    fig.savefig(out_png, dpi=300)
    fig.savefig(out_pdf)
    plt.close(fig)
    print(f"Saved combined {metric_col} plot to {out_png}")


def main() -> None:
    args = parse_args()

    out_dir = args.output_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    if args.base_dir is not None:
        base_dirs = [args.base_dir]
    else:
        base_dirs = _discover_base_dirs()
    if not base_dirs:
        raise RuntimeError("No core_nll_* directories found.")

    combined_parts: Dict[str, List[pd.DataFrame]] = {
        m[0]: [] for m in METRICS
    }

    for key, label, metrics_fname in NETWORKS:
        parts: List[pd.DataFrame] = []
        for base_dir in base_dirs:
            metrics_path = base_dir / "metrics" / metrics_fname
            if not metrics_path.exists():
                continue
            features = load_features(base_dir)
            cohorts = build_cohort_table(base_dir, features)
            if cohorts.empty:
                print(
                    f"  {base_dir.name}: no incoming cohort node sets found — "
                    "run create_highlow_incoming_weight_nodesets.py first."
                )
                continue

            metrics_df = load_metrics_table(metrics_path)
            node_ids = _load_node_ids(base_dir)
            sparsity_series = load_sparsity(base_dir, node_ids, key)
            sparsity_df = sparsity_series.reset_index()
            feature_metrics_base = features[["image_selectivity"]].reset_index()

            merged = cohorts.merge(metrics_df, on="node_id", how="inner")
            merged = merged.merge(feature_metrics_base, on="node_id", how="left")
            merged = merged.merge(sparsity_df, on="node_id", how="left")
            if merged.empty:
                continue
            merged["_base_dir"] = base_dir.name
            parts.append(merged)

        if not parts:
            print(f"{label}: no matching neurons; skipping")
            continue

        merged = pd.concat(parts, ignore_index=True)
        print(
            f"{label}: {len(merged)} core neurons (aggregated). cohort counts:\n"
            f"{merged.groupby(['cell_class', 'cohort']).size()}"
        )

        for metric_col, metric_label, filename_prefix in METRICS:
            if metric_col not in merged.columns:
                print(f"{label}: metric '{metric_col}' missing; skipping")
                continue

            plot_df = merged.dropna(subset=[metric_col]).copy()
            if plot_df.empty:
                print(f"{label}: no valid data for {metric_col}")
                continue
            if not args.combined_only:
                make_boxplot(
                    plot_df,
                    f"Core {metric_label} ({label}) — incoming cohorts",
                    metric_col,
                    metric_label,
                    f"{filename_prefix}_{key}",
                    out_dir=out_dir,
                )

            training_status = TRAINING_LABELS.get(key, key)
            combined = plot_df.copy()
            combined["training_status"] = training_status
            combined["cell_class_training"] = combined["cell_class"].apply(
                lambda c: f"{c} ({training_status})"
            )
            combined_parts[metric_col].append(combined)

    showfliers = not args.hide_outliers

    out_suffix = ""
    if not showfliers:
        out_suffix += "_no_outliers"
    out_suffix += "_celltype_first" if args.group_order == "celltype_first" else ""

    for metric_col, metric_label, filename_prefix in METRICS:
        parts = combined_parts.get(metric_col, [])
        if not parts:
            continue

        combined_df = pd.concat(parts, ignore_index=True)

        ylim = None
        if metric_col == "rate":
            ylim = (0, FR_YMAX)
        elif metric_col in ["OSI", "DSI", "dg_sparsity", "image_selectivity"]:
            ylim = (0, 1)

        make_combined_boxplot(
            combined_df,
            metric_col,
            metric_label,
            filename_prefix,
            out_dir=out_dir,
            out_suffix=out_suffix,
            showfliers=showfliers,
            group_order=args.group_order,
            ylim=ylim,
        )


if __name__ == "__main__":
    main()
