channels:
  - conda-forge
  - bioconda
  - kaeldai

dependencies:
  # Basics ------------------
  # 3.12 is not compatible with allensdk (as of 7/1/2024)
  - python=3.11
  - pip

  # Nest   ------------------
  - nest-simulator
    
  # Convenience -------------
  - black
  - iminuit
  - snakemake
  - jupyter
  - pandarallel
  
  # bmtk
  - pytest
  - mpi4py
  - bmtk
  - numba
  
  # modeling
  - openpyxl

  # allensdk
  - future
  - jinja2
  - nest-asyncio
  - psycopg2-binary
  - pynrrd
  - python-dateutil
  - pytables
  - requests
  - scikit-build
  - scikit-image
  - scipy
  - seaborn
  - semver
  - simpleitk
  - simplejson
  - six
  - sqlalchemy
  - tqdm
  - xarray

  
  # PIP dependencies
  - pip:
    # for modeling
    - allensdk
    - pylightxl
    - sonata