# general utilities for the project.
pop_name_to_syn_type = {
    "i1Htr3a": "vip",
    "e23Cux2": "e23",
    "i23Vip": "vip",
    "i23Pvalb": "pv",
    "i23Sst": "sst",
    "e4Nr5a1": "e4",
    "e4Rorb": "e4",
    "e4Scnn1a": "e4",
    "e4other": "e4",
    "i4Vip": "vip",
    "i4Pvalb": "pv",
    "i4Sst": "sst",
    "e5IT": "e5it",
    "e5ET": "e5et",
    "e5NP": "e5np",
    "i5Vip": "vip",
    "i5Pvalb": "pv",
    "i5Sst": "sst",
    "e6Ntsr1": "e6",
    "i6Vip": "vip",
    "i6Pvalb": "pv",
    "i6Sst": "sst",
}
