#!/usr/bin/env python3
"""Generate 8dir_10trials config sets for outgoing-cohort silencing (Fig. 5).

This is the multi-network analog of the existing `core_nll_0/configs/8dir_10trials_*` layout.

It writes:
  <base_dir>/configs/8dir_10trials_<condition>/config_{0..79}.json

Conditions supported (matching Fig.5 heatmap scripts):
- exc_high_core_neg1000
- exc_low_core_neg1000
- inh_high_core_neg1000
- inh_low_core_neg1000

Each config embeds the node ids directly under config["node_sets"], exactly like the existing
`core_nll_0/configs/8dir_10trials_exc_high_core_neg1000/config_0.json`.

Prerequisites per base_dir:
- `<base_dir>/node_sets/high_outgoing_exc_core_nodes.json` etc. (generated by
  `analysis_shared/create_highlow_outgoing_weight_nodesets.py`)
- Existing stimulus input directories:
  - `<base_dir>/filternet_8dir_10trials/angle{0..315}_trial{0..9}`
  - `<base_dir>/bkg_8dir_10trials/angle{0..315}_trial{0..9}`

Usage:
  python -m analysis_shared.generate_fig5_outgoing_silencing_configs --base-dir core_nll_3

"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np


CONDITIONS = {
    "exc_high_core_neg1000": {
        "nodeset_file": "high_outgoing_exc_core_nodes.json",
        "clamp_key": "ExcHighOutgoingClamp",
        "nodeset_name": "exc_high_outgoing",
        "amp": -1000.0,
    },
    "exc_low_core_neg1000": {
        "nodeset_file": "low_outgoing_exc_core_nodes.json",
        "clamp_key": "ExcLowOutgoingClamp",
        "nodeset_name": "exc_low_outgoing",
        "amp": -1000.0,
    },
    "inh_high_core_neg1000": {
        "nodeset_file": "high_outgoing_inh_core_nodes.json",
        "clamp_key": "InhHighOutgoingClamp",
        "nodeset_name": "inh_high_outgoing",
        "amp": -1000.0,
    },
    "inh_low_core_neg1000": {
        "nodeset_file": "low_outgoing_inh_core_nodes.json",
        "clamp_key": "InhLowOutgoingClamp",
        "nodeset_name": "inh_low_outgoing",
        "amp": -1000.0,
    },
}


def _load_node_ids(node_sets_dir: Path, filename: str) -> list[int]:
    path = node_sets_dir / filename
    if not path.exists():
        raise FileNotFoundError(f"Missing node set: {path}")
    data = json.loads(path.read_text())
    return [int(x) for x in data.get("node_id", [])]


def _base_config() -> dict:
    return {
        "manifest": {
            "$BASE_DIR": "${configdir}/../..",
            "$NETWORK_DIR": "$BASE_DIR/network",
            "$MODELS_DIR": "$BASE_DIR/components",
            "$OUTPUT_DIR": None,
            "$LGNINPUT_DIR": None,
            "$BKGINPUT_DIR": None,
        },
        "run": {"duration": 3000.0, "dt": 0.25, "block_run": False, "block_size": 1000.0},
        "inputs": {
            "LGN_spikes": {
                "input_type": "spikes",
                "module": "h5",
                "input_file": "$LGNINPUT_DIR/spikes.h5",
                "node_set": "lgn",
            },
            "BKG_spikes": {
                "input_type": "spikes",
                "module": "h5",
                "input_file": "$BKGINPUT_DIR/bkg_spikes_250Hz_3s.h5",
                "node_set": "bkg",
            },
        },
        "output": {
            "log_file": "log.txt",
            "spikes_file": "spikes.h5",
            "spikes_file_csv": "spikes.csv",
            "output_dir": "$OUTPUT_DIR",
            "overwrite_output_dir": True,
            "quiet_simulator": True,
        },
        "target_simulator": "NEST",
        "components": {
            "point_neuron_models_dir": "$MODELS_DIR/cell_models",
            "synaptic_models_dir": "$MODELS_DIR/synaptic_models",
        },
        "networks": {
            "nodes": [
                {"nodes_file": "$NETWORK_DIR/v1_nodes.h5", "node_types_file": "$NETWORK_DIR/v1_node_types.csv"},
                {"nodes_file": "$NETWORK_DIR/lgn_nodes.h5", "node_types_file": "$NETWORK_DIR/lgn_node_types.csv"},
                {"nodes_file": "$NETWORK_DIR/bkg_nodes.h5", "node_types_file": "$NETWORK_DIR/bkg_node_types.csv"},
            ],
            "edges": [
                {"edges_file": "$NETWORK_DIR/v1_v1_edges_bio_trained.h5", "edge_types_file": "$NETWORK_DIR/v1_v1_edge_types.csv"},
                {"edges_file": "$NETWORK_DIR/lgn_v1_edges.h5", "edge_types_file": "$NETWORK_DIR/lgn_v1_edge_types.csv"},
                {"edges_file": "$NETWORK_DIR/bkg_v1_edges_bio_trained.h5", "edge_types_file": "$NETWORK_DIR/bkg_v1_edge_types.csv"},
            ],
        },
        "node_sets": {},
    }


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(
        description="Generate 8dir_10trials outgoing-cohort silencing configs for Fig.5."
    )
    ap.add_argument(
        "--base-dir",
        type=Path,
        required=True,
        help="Network base directory (e.g., core_nll_3)",
    )
    ap.add_argument(
        "--condition",
        choices=sorted(CONDITIONS),
        default=None,
        help="If provided, only generate configs for this condition.",
    )
    ap.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing config_{i}.json files.",
    )
    return ap.parse_args()


def generate_condition(base_dir: Path, condition: str, overwrite: bool) -> int:
    spec = CONDITIONS[condition]
    node_sets_dir = base_dir / "node_sets"
    nodes = _load_node_ids(node_sets_dir, spec["nodeset_file"])
    if not nodes:
        raise RuntimeError(f"Node set is empty: {node_sets_dir / spec['nodeset_file']}")

    cfg_dir = base_dir / "configs" / f"8dir_10trials_{condition}"
    cfg_dir.mkdir(parents=True, exist_ok=True)

    angles = list(range(0, 360, 45))
    trials = list(range(10))

    idx = 0
    for angle in angles:
        for trial in trials:
            cfg = _base_config()
            cfg["manifest"]["$LGNINPUT_DIR"] = f"$BASE_DIR/filternet_8dir_10trials/angle{angle}_trial{trial}"
            cfg["manifest"]["$BKGINPUT_DIR"] = f"$BASE_DIR/bkg_8dir_10trials/angle{angle}_trial{trial}"
            cfg["manifest"]["$OUTPUT_DIR"] = f"$BASE_DIR/8dir_10trials_{condition}/angle{angle}_trial{trial}"

            cfg["inputs"][spec["clamp_key"]] = {
                "input_type": "current_clamp",
                "module": "IClamp",
                "node_set": spec["nodeset_name"],
                "amp": float(spec["amp"]),
                "delay": 1.0,
                "duration": 2999.0,
            }
            cfg["node_sets"][spec["nodeset_name"]] = {
                "population": "v1",
                "node_id": nodes,
            }

            out_path = cfg_dir / f"config_{idx}.json"
            if out_path.exists() and not overwrite:
                idx += 1
                continue
            out_path.write_text(json.dumps(cfg, indent=2))
            idx += 1

    return idx


def main() -> None:
    args = parse_args()
    base_dir = args.base_dir
    if not base_dir.exists():
        raise FileNotFoundError(base_dir)

    conds = [args.condition] if args.condition else list(CONDITIONS)
    for cond in conds:
        n = generate_condition(base_dir, cond, args.overwrite)
        print(f"Generated {n} configs: {base_dir}/configs/8dir_10trials_{cond}")


if __name__ == "__main__":
    main()
